from PyQt5.QtWidgets import QTreeWidget, QTreeWidgetItem


class vehicleInfoTree(QTreeWidget):
    def __init__(self, parent):
        super().__init__(parent)
        self.initUI()

    def initUI(self):
        self.setAlternatingRowColors(True)
        self.header().setVisible(False)
        self.tw = QTreeWidget(self)
        self.tw.setColumnCount(2)
        self.tw.setHeaderLabels(["Topic", "Data"])
        self.root = self.tw.invisibleRootItem()

        item = QTreeWidgetItem()
        item.setText(0, "IMU")
        itemChild1 = QTreeWidgetItem(item)
        itemChild1.setText(0, "Fruit")
        # itemChild1.setText(1, "ad")
        self.root.addChild(item)

        # item = QTreeWidgetItem()
        # item.setText(0, "Vegetable")
        # item.setText(1, "Carrot")
        # self.root.addChild(item)
        # tw = QTreeWidget(self)
        # tw.setColumnCount(2)
        # tw.setHeaderLabels(["Topic", "Data"])
        # itemTop1 = QTreeWidgetItem(self)
        # itemTop1.setText(0, "IMU")
        # itemChild1 = QTreeWidgetItem(itemTop1)
        # itemChild1.setText(0, "ChildTest1")
        # itemChild2 = QTreeWidgetItem(itemTop1)
        # itemChild2.setText(0, "ChildTest2")
        # itemTop1 = QTreeWidgetItem(self)
        # itemTop1.setText(0, "CAM")
        # itemChild1 = QTreeWidgetItem(itemTop1)
        # itemChild1.setText(0, "ChildTest1")
        # itemChild2 = QTreeWidgetItem(itemTop1)
        # itemChild2.setText(0, "ChildTest2")
        # itemTop1 = QTreeWidgetItem(self)
        # itemTop1.setText(0, "Velodyne")
        # itemChild1 = QTreeWidgetItem(itemTop1)
        # itemChild1.setText(0, "ChildTest1")
        # itemChild2 = QTreeWidgetItem(itemTop1)
        # itemChild2.setText(0, "ChildTest2")
        # itemTop1 = QTreeWidgetItem(self)
        # itemTop1.setText(0, "Moter_Speed")
        # itemChild1 = QTreeWidgetItem(itemTop1)
        # itemChild1.setText(0, "ChildTest1")
        # itemChild2 = QTreeWidgetItem(itemTop1)
        # itemChild2.setText(0, "ChildTest2")
        # itemTop1 = QTreeWidgetItem(self)
        # itemTop1.setText(0, "Servo_Position")
        # itemChild1 = QTreeWidgetItem(itemTop1)
        # itemChild1.setText(0, "ChildTest1")
        # itemChild2 = QTreeWidgetItem(itemTop1)
        # itemChild2.setText(0, "ChildTest2")